// docker.js — Dockerfile / compose generators for ObserverLauncher (v3.1.0 Phase D).
//
// WHY: the headless core (src/headless.js) + /health (C2) + OBSERVER_DATA_DIR (B1) already let the
// SAME backend run with no window on a VPS. Docker is the packaging step on top: a baked JDK, the
// server folder as a volume, the data dir as a separate volume, and a healthcheck. This module is
// PURE — it only builds strings; the caller (CLI `observer docker create`) writes them to disk, so
// the output is trivially unit-testable.
//
// Process model (decided in the 3.0.0 plan): the launcher is PID 1 inside the container and spawns
// the JVM as a child (spawnServerProcess already does exactly that), so no special entrypoint is
// needed beyond running the headless entry point.

// Map a server type to the wizard's software id (they match today, but keep it explicit so a rename
// in one place cannot silently break the generated Dockerfile).
const TYPE_TO_SOFTWARE = { vanilla: 'vanilla', paper: 'paper', purpur: 'purpur', leaf: 'leaf', fabric: 'fabric', forge: 'forge', neoforge: 'neoforge', spigot: 'spigot' };

function normalizeOpts(opts) {
  opts = opts || {};
  const type = String(opts.type || 'paper').toLowerCase();
  return {
    type: TYPE_TO_SOFTWARE[type] ? type : 'paper',
    version: opts.version ? String(opts.version).trim() : 'latest',
    ram: Math.max(1, Math.min(64, Number(opts.ram) || 4)),
    port: Number.isInteger(Number(opts.port)) && Number(opts.port) >= 1 && Number(opts.port) <= 65535 ? Number(opts.port) : 25565,
    javaVersion: Number(opts.javaVersion) || 21,
    mods: Array.isArray(opts.mods) ? opts.mods.map(m => String(m).trim()).filter(Boolean) : [],
  };
}

// The Dockerfile. Bakes a JRE (so the in-container auto-install of java.js is never needed), copies
// the app, and runs the headless entry point. The server folder and the data dir are volumes, so the
// image itself stays small and disposable.
function dockerfile(opts) {
  const o = normalizeOpts(opts);
  return `# ObserverLauncher ${o.type} ${o.version} — generated by \`observer docker create\`.
# Build:  docker build -t observerlauncher-server .
# Run:    docker compose up -d
#
# The launcher is PID 1 and spawns the JVM as a child (see src/main/server-lifecycle.js).
FROM eclipse-temurin:${o.javaVersion}-jre

# Node.js is required to run the headless entry point (the app itself, not the server).
RUN apt-get update && apt-get install -y --no-install-recommends nodejs npm zip unzip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
# BUGFIX (v3.1.0): install RUNTIME deps FIRST. .dockerignore excludes node_modules, and players.js
# requires prismarine-nbt (a runtime dependency), so without this the container crash-looped with
# MODULE_NOT_FOUND the moment headless.js loaded. Copy the lockfile + package.json, npm ci --omit=dev,
# and only THEN copy the source (better layer caching too).
COPY package.json package-lock.json ./
RUN npm ci --omit=dev
COPY . /app

# The server folder (world/plugins/mods/configs) and the launcher data dir are volumes, so they
# survive container rebuilds and are never baked into the image.
ENV OBSERVER_DATA_DIR=/data \
    OBSERVER_CONFIRM_MODE=auto-deny \
    NODE_ENV=production

EXPOSE ${o.port}

# Healthcheck: confirm the headless process (PID 1) is still alive. Cheap — it does NOT boot a second
# backend on every interval (the old healthcheck ran the CLI, which was wasteful at a 30s cadence).
HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \
  CMD sh -c "tr '\\0' ' ' </proc/1/cmdline | grep -q headless.js" || exit 1

ENTRYPOINT ["node", "src/headless.js"]
`;
}

// docker-compose.yml: two named volumes (server + data), the port mapping, restart policy and the
// same healthcheck. Uses bind mounts so the user can edit server files directly on the host.
function composeFile(opts) {
  const o = normalizeOpts(opts);
  return `# ObserverLauncher ${o.type} ${o.version} — generated by \`observer docker create\`.
# Edit ./server (world, plugins, mods, server.properties) and ./data (settings.json) on the host;
# both are mounted into the container. Then: docker compose up -d
services:
  server:
    build: .
    image: observerlauncher-${o.type}
    container_name: observerlauncher-${o.type}
    restart: unless-stopped
    ports:
      - "${o.port}:${o.port}"
    volumes:
      - ./server:/server
      - ./data:/data
    environment:
      OBSERVER_DATA_DIR: /data
      OBSERVER_SERVER_DIR: /server
      OBSERVER_CONFIRM_MODE: auto-deny
    healthcheck:
      test: ["CMD", "node", "src/cli.js", "status"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3
`;
}

// .dockerignore keeps the build context small and never ships local secrets/data into the image.
function dockerignore() {
  return [
    '.git', 'node_modules', 'tests', '.agent', 'docs', 'website',
    'data', 'server', 'docker-*', '*.log', '.github',
    'build', 'test-results', 'playwright-report',
  ].join('\n') + '\n';
}

// A short host-side README written next to the generated files.
function readme(opts) {
  const o = normalizeOpts(opts);
  // Sanitize the mod list for the README (strip newlines/control chars so a crafted --mods value
  // cannot inject Markdown lines — cosmetic, but cheap).
  const safeMods = o.mods.map(m => m.replace(/[\r\n\t]+/g, ' ').slice(0, 80));
  const mods = safeMods.length ? `\n\nRequested mods/plugins: ${safeMods.join(', ')}. Install them with \`observer install <id>\` (MCP) or drop the jars into ./server/mods (or ./server/plugins) before starting.` : '';
  return `# ObserverLauncher — ${o.type} server (Docker)

Generated by \`observer docker create --type ${o.type} --ram ${o.ram}G --port ${o.port}\`.

## First run

1. Put a server jar (or run.sh) in \`./server/\`, or let the wizard create it from the GUI. The
   container downloads nothing by itself on first boot.
2. \`docker compose up -d\`
3. \`docker compose logs -f\` to watch the server start.

The launcher runs headless inside the container; the server folder (\`./server\`) and the data dir
(\`./data\`, holding settings.json) are volumes, so they persist across rebuilds.${mods}

## Notes

- Java ${o.javaVersion} is baked into the image — no runtime Java download inside the container.
- The MCP server binds 127.0.0.1 INSIDE the container on a RANDOM port, so publishing a port does
  NOT reach it. To use MCP with this container, run the bridge inside it, e.g.
  docker exec -it <container> node src/mcp/bridge.js (its config/token is the volume file
  ./data/mcp-bridge.json), or set a fixed MCP port and a network the client can reach. Do NOT expose
  MCP to the internet.
- Edit \`server.properties\` in \`./server\` to change the port; keep the compose port mapping in sync.
`;
}

module.exports = { dockerfile, composeFile, dockerignore, readme, normalizeOpts, TYPE_TO_SOFTWARE };
