// scripts/fetch-fonts.js - bundle the UI + mono fonts for offline use (v4.0.0, DESIGN.md 5.1).
//
// WHY: the app must render with NO network. The old Google Fonts @import is gone, so this copies
// prebuilt woff2 files from the @fontsource packages (installed with npm) into
// src/renderer/assets/fonts/ and writes a fonts.css with the correct @font-face + unicode-range.
// Using the per-script subsets (each with its unicode-range) means Latin, Vietnamese and Cyrillic
// all render in the real font; anything missing falls back per-glyph.
//
// USAGE (one time, on a machine with network):
//   npm i --no-save @fontsource-variable/manrope @fontsource/ibm-plex-mono
//   node scripts/fetch-fonts.js
// Then reload the app (npm start). The fonts are committed under assets/ and ship in the asar.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'renderer', 'assets', 'fonts');
const MODULES = path.join(ROOT, 'node_modules');

// The family names MUST match src/renderer/css/01-tokens.css (--font-ui / --font-mono).
// Fontsource's variable package calls Manrope 'Manrope Variable' - we rewrite it to 'Manrope'.
const JOBS = [
  { pkg: '@fontsource-variable/manrope', family: 'Manrope Variable', renameTo: 'Manrope', css: ['index.css'] },
  { pkg: '@fontsource/ibm-plex-mono', family: 'IBM Plex Mono', renameTo: 'IBM Plex Mono', css: ['500.css', '600.css', '700.css'] },
];

function processCss(raw, family, renameTo) {
  let css = raw;
  if (renameTo && renameTo !== family) css = css.split(family).join(renameTo);
  // strip the .woff fallback (we only copy .woff2) and point every url at the flat file name.
  // Keep each source's own `format(...)` (Manrope = woff2-variations, IBM Plex Mono = woff2), just
  // flatten the path to the file name in this folder and drop the .woff fallback.
  css = css.replace(/src:([^;]+);/g, (_, decl) => {
    const parts = [...decl.matchAll(/url\(([^)]+\.woff2)\)\s*(format\([^)]*\))?/g)].map(m => `url('./${path.basename(m[1])}')${m[2] ? ' ' + m[2] : ''}`);
    return 'src:' + parts.join(', ') + ';';
  });
  return css;
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  let css = '/* GENERATED by scripts/fetch-fonts.js - do not edit by hand. */\n';
  let copied = 0;
  const missing = [];
  for (const job of JOBS) {
    const dir = path.join(MODULES, job.pkg);
    const filesDir = path.join(dir, 'files');
    if (!fs.existsSync(filesDir)) { missing.push(job.pkg); continue; }
    for (const cssName of job.css) {
      const cssPath = path.join(dir, cssName);
      if (!fs.existsSync(cssPath)) { missing.push(`${job.pkg}/${cssName}`); continue; }
      const raw = fs.readFileSync(cssPath, 'utf8');
      for (const m of raw.matchAll(/url\(([^)]+\.woff2)\)/g)) {
        const base = path.basename(m[1]);
        const src = path.join(filesDir, base);
        if (fs.existsSync(src) && !fs.existsSync(path.join(OUT, base))) { fs.copyFileSync(src, path.join(OUT, base)); copied++; }
      }
      css += processCss(raw, job.family, job.renameTo) + '\n';
    }
  }
  fs.writeFileSync(path.join(OUT, 'fonts.css'), css);
  console.log(`fonts: copied ${copied} woff2 file(s), wrote assets/fonts/fonts.css`);
  if (missing.length) {
    console.log('MISSING - install the packages first:');
    console.log('  npm i --no-save @fontsource-variable/manrope @fontsource/ibm-plex-mono');
    for (const m of missing) console.log('  - ' + m);
  }
}

main();
