const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('observer', {
  getState: () => ipcRenderer.invoke('settings:get'), getFiles: () => ipcRenderer.invoke('files:get'), pickFolder: opts => ipcRenderer.invoke('dialog:server-folder', opts), saveSettings: s => ipcRenderer.invoke('settings:save', s), onboardingComplete: () => ipcRenderer.invoke('onboarding:complete'),
  start: s => ipcRenderer.invoke('server:start', s), stop: () => ipcRenderer.invoke('server:stop'), command: c => ipcRenderer.invoke('server:command', c), openFiles: p => ipcRenderer.invoke('files:open', p), saveProperties: p => ipcRenderer.invoke('properties:save', p), readRawProperties: () => ipcRenderer.invoke('properties:raw-get'), saveRawProperties: content => ipcRenderer.invoke('properties:raw-save', content),
  importContent: type => ipcRenderer.invoke('content:import', type), deleteContent: config => ipcRenderer.invoke('content:delete', config), editorOpen: rel => ipcRenderer.invoke('editor:open', rel), editorSave: payload => ipcRenderer.invoke('editor:save', payload), editorList: () => ipcRenderer.invoke('editor:list'),   createBackup: () => ipcRenderer.invoke('backup:create'), restoreBackup: name => ipcRenderer.invoke('backup:restore', name), deleteBackup: name => ipcRenderer.invoke('backup:delete', name), worldmapLoad: () => ipcRenderer.invoke('worldmap:load'), worldmapSetWaypoints: list => ipcRenderer.invoke('worldmap:waypoints:set', list), worldmapChunks: dim => ipcRenderer.invoke('worldmap:chunks', dim),
  marketVersions: () => ipcRenderer.invoke('market:versions'), marketSearch: query => ipcRenderer.invoke('market:search', query), marketInstall: item => ipcRenderer.invoke('market:install', item), marketDetail: item => ipcRenderer.invoke('market:detail', item), wizardCreate: config => ipcRenderer.invoke('wizard:create', config), wizardVersions: software => ipcRenderer.invoke('wizard:versions', software), wizardJavaCheck: payload => ipcRenderer.invoke('wizard:java-check', payload), importModpack: () => ipcRenderer.invoke('modpack:import'), exportModpack: () => ipcRenderer.invoke('modpack:export'), installMarketModpack: config => ipcRenderer.invoke('modpack:install-from-market', config), playerRead: uuid => ipcRenderer.invoke('player:read', uuid), playerSave: config => ipcRenderer.invoke('player:save', config), playerWhitelistToggle: config => ipcRenderer.invoke('player:whitelist-toggle', config), playerBanToggle: config => ipcRenderer.invoke('player:ban-toggle', config), playerOpToggle: config => ipcRenderer.invoke('player:op-toggle', config),
  networkInfo: () => ipcRenderer.invoke('network:info'), checkPublicIp: () => ipcRenderer.invoke('network:public-ip'), allowFirewall: port => ipcRenderer.invoke('network:allow-firewall', port), javaAutoInstall: () => ipcRenderer.invoke('java:auto-install'),
  onLog: cb => ipcRenderer.on('server:log', (_, d) => cb(d)), onState: cb => ipcRenderer.on('server:state', (_, d) => cb(d)), onMetrics: cb => ipcRenderer.on('server:metrics', (_, d) => cb(d)), onLive: cb => ipcRenderer.on('server:live', (_, d) => cb(d)), onFiles: cb => ipcRenderer.on('server:files', (_, d) => cb(d)), onBuildDone: cb => ipcRenderer.on('wizard:build-done', (_, d) => cb(d)), onWizardProgress: cb => ipcRenderer.on('wizard:progress', (_, d) => cb(d)), onJavaProgress: cb => ipcRenderer.on('java:progress', (_, d) => cb(d)), onMarketProgress: cb => ipcRenderer.on('market:progress', (_, d) => cb(d)), onIconsUpdate: cb => ipcRenderer.on('icons:update', (_, d) => cb(d)), onEditorExternal: cb => ipcRenderer.on('editor:external', (_, d) => cb(d)),
  checkUpdate: () => ipcRenderer.invoke('app:check-update'),
  downloadUpdate: () => ipcRenderer.invoke('app:download-update'),
  quitInstall: () => ipcRenderer.invoke('app:quit-install'),
  onUpdateAvailable: cb => ipcRenderer.on('app:update-available', (_, d) => cb(d)),
  onUpdateProgress: cb => ipcRenderer.on('app:update-progress', (_, d) => cb(d)),
  onUpdateDownloaded: cb => ipcRenderer.on('app:update-downloaded', (_, d) => cb(d)),
  onUpdateNone: cb => ipcRenderer.on('app:update-none', (_, d) => cb(d))
});
